Kernel recipe: fixup devtool error
if (os.path.exists(srcdir) and os.listdir(srcdir)) and (kernelVersion in staging_kerVer and staging_kbranch == kbranch):
TypeError: 'in <string>' requires string as left operand, not NoneType