.github/build: set umask
In hardened enviroments, the umask is set to a more restrictive value
through the systemd UMask parameter , but can be adjusted at the
execution level. If not set and under such circuntances, will trigger

  ERROR:  OE-core's config sanity checker detected ....
    Please use a umask which allows a+rx and u+rwx

Signed-off-by: Jorge Marques <jorge.marques@analog.com>